/**
 * Auto-generated TypeScript bindings for Tauri commands
 * Generated by tauri-typegen v0.5.0
 * Generated at: 2026-04-22T14:40:45.686431900+00:00
 * Generator: none
 *
 * Do not edit manually - regenerate using: cargo tauri-typegen generate
 */

import { invoke } from '@tauri-apps/api/core';
import * as types from './types';


export async function getInputDeviceList(): Promise<types.AudioDeviceDto[]> {
  return invoke('get_input_device_list');
}



export async function getOutputDeviceList(): Promise<types.AudioDeviceDto[]> {
  return invoke('get_output_device_list');
}


export async function setInputDevice(params: types.SetInputDeviceParams): Promise<void> {
  return invoke('set_input_device', params);
}


export async function setOutputDevice(params: types.SetOutputDeviceParams): Promise<void> {
  return invoke('set_output_device', params);
}



export async function startLoopback(): Promise<void> {
  return invoke('start_loopback');
}


export async function toggleOnOff(params: types.ToggleOnOffParams): Promise<void> {
  return invoke('toggle_on_off', params);
}


export async function setGain(params: types.SetGainParams): Promise<void> {
  return invoke('set_gain', params);
}


export async function setMasterVolume(params: types.SetMasterVolumeParams): Promise<void> {
  return invoke('set_master_volume', params);
}


export async function setToneStack(params: types.SetToneStackParams): Promise<void> {
  return invoke('set_tone_stack', params);
}


export async function setBass(params: types.SetBassParams): Promise<void> {
  return invoke('set_bass', params);
}


export async function setMiddle(params: types.SetMiddleParams): Promise<void> {
  return invoke('set_middle', params);
}


export async function setTreble(params: types.SetTrebleParams): Promise<void> {
  return invoke('set_treble', params);
}


