/**
 * Auto-generated TypeScript bindings for Tauri commands
 * Generated by tauri-typegen v0.5.0
 * Generated at: 2026-04-21T11:01:09.686643900+00:00
 * Generator: none
 *
 * Do not edit manually - regenerate using: cargo tauri-typegen generate
 */

import { invoke } from '@tauri-apps/api/core';
import * as types from './types';


export async function startLoopback(): Promise<void> {
  return invoke('start_loopback');
}



export async function getInputDeviceList(): Promise<types.AudioDeviceDto[]> {
  return invoke('get_input_device_list');
}



export async function getOutputDeviceList(): Promise<types.AudioDeviceDto[]> {
  return invoke('get_output_device_list');
}


