/**
 * Auto-generated TypeScript bindings for Tauri commands
 * Generated by tauri-typegen v0.5.0
 * Generated at: 2026-04-21T13:49:42.274071900+00:00
 * Generator: none
 *
 * Do not edit manually - regenerate using: cargo tauri-typegen generate
 */



export interface AudioDeviceDto {
  id: string;
  name: string;
}



export interface SetInputDeviceParams {
  deviceId: string;
  [key: string]: unknown;
}


export interface SetOutputDeviceParams {
  deviceId: string;
  [key: string]: unknown;
}


export interface SetGainParams {
  gain: number;
  [key: string]: unknown;
}



