/**
 * Auto-generated TypeScript bindings for Tauri commands
 * Generated by tauri-typegen v0.5.0
 * Generated at: 2026-04-22T12:47:35.557929700+00:00
 * Generator: none
 *
 * Do not edit manually - regenerate using: cargo tauri-typegen generate
 */



export interface ToneStackDto {
  bass: number;
  middle: number;
  treble: number;
}

export interface AudioDeviceDto {
  id: string;
  name: string;
}



export interface SetInputDeviceParams {
  deviceId: string;
  [key: string]: unknown;
}


export interface SetOutputDeviceParams {
  deviceId: string;
  [key: string]: unknown;
}


export interface SetGainParams {
  gain: number;
  [key: string]: unknown;
}


export interface SetMasterVolumeParams {
  masterVolume: number;
  [key: string]: unknown;
}


export interface SetToneStackParams {
  toneStack: ToneStackDto;
  [key: string]: unknown;
}


export interface SetBassParams {
  bass: number;
  [key: string]: unknown;
}


export interface SetMiddleParams {
  middle: number;
  [key: string]: unknown;
}


export interface SetTrebleParams {
  treble: number;
  [key: string]: unknown;
}



