// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {FlipEffectDto} from "./FlipEffectDto";
import type {HcDistortionDto} from "./HcDistortionDto";

/**
 * A serialisable, tagged representation of any effect in the signal chain.
 *
 * Uses serde's adjacently-tagged format so that both the Rust serialisation
 * and the TypeScript typegen agree on the wire shape:
 *
 * ```json
 * { "kind": "Flip",         "data": { "id": 1, "name": "Flip",  "is_active": true,  "color": "#e74c3c" } }
 * { "kind": "HCDistortion", "data": { "id": 2, "name": "Dist",  "is_active": false, "color": "#e67e22", "threshold": 0.5 } }
 * ```
 *
 * Adding a new effect = new variant + new `*Dto` struct in its own file.
 */
export type EffectDto = { "kind": "Flip", "data": FlipEffectDto } | { "kind": "HCDistortion", "data": HcDistortionDto };
