// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * DTO for [`FlipEffect`](crate::services::effects::flip_effect::FlipEffect).
 */
export type FlipEffectDto = { id: number, name: string, is_active: boolean, 
/**
 * UI colour for the pedal chassis (hex string, e.g. `"#e74c3c"`).
 */
color: string, };
