// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * DTO for [`HCDistortion`](crate::services::effects::distortion::hc_distortion::HCDistortion).
 */
export type HcDistortionDto = { id: number, name: string, is_active: boolean, 
/**
 * UI colour for the pedal chassis (hex string, e.g. `"#e67e22"`).
 */
color: string, 
/**
 * Hard-clip threshold in the range `(0.0, 1.0]`.
 * Lower values produce heavier distortion.
 */
threshold: number, };
