// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IrProfileDto = { file_name: string, label: string, is_custom: boolean, is_in_use: boolean, };
